server:
  port: 8080

spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  # image upload
  servlet.multipart.max-file-size: 3MB
  servlet.multipart.max-request-size: 3MB

  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show_sql: true



