spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${redis.host:localhost} # 기본값을 localhost로 설정
    port: ${redis.port:6379}      # 기본값을 6379로 설정

upload:
  image:
    location: C:/Users/user/image/ # window 경로
              # /Users/user/image/ mac or linux 경로

jwt:
  secret: "IqUESdB4c3m7iFDLQOeibqaNpjp107hFAEdTIxZVzrLZKdREEbQrKknqs5Y4bDqlbbOK18b5z/mgllCelOhUKw=="