server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG


spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #use_sql_comments: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # about swagger

  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB


